### ISSUE TITLE
Ability to fetch relative URLs

### ISSUE THREAD

**Issue by codehate** [mvdan/xurls#13]
Would be great if there is ability to fetch relative URLs.

```html
<!-- http://foobar.com -->
 <a href="foobar.html">The Wonderful World of Foobar!</a>
 <a href="http://google.com/foobar.html">The Wonderful World of Foobar!</a>
```

This should return both: 

- `http://google.com/foobar.html`
- `http://foobar.com/foobar.html`

**Comment by mvdan** [comment]
This would require for xulrs to understand HTML, which is outside of its scope.
