### ISSUE TITLE
Japanese URL not matched fully

### ISSUE THREAD

**Issue by j605** [mvdan/xurls#17]
I just have one example which was shared by someone, `https://ja.wikipedia.org/wiki/日本語` where the URL cuts of after `日`.

**Comment by mvdan** [comment]
What version are you running on? This works fine on master:

```
 $ echo https://ja.wikipedia.org/wiki/日本語 | xurls
https://ja.wikipedia.org/wiki/日本語
```

This has been likely fixed recently, like in https://github.com/mvdan/xurls/commit/a3c802b2dc0a2f781b8401749ff34db5097cb867. If you're already running 1.1.0, then it may have been fixed in an even more recent commit.

**Comment by j605** [comment]
Sorry for not testing it directly. It doesn't work in st with `externalpipe` patch so I will close this issue. Thanks!

**Comment by mvdan** [comment]
You're absolutely correct - it's broken here too :) Seems like a bug somewhere else, like in `st`, the externalpipe patch or perhaps even `dmenu`.
