### ISSUE TITLE
SSL certificate for mvdan.cc has expired

### ISSUE THREAD

**Issue by rubyroobs** [mvdan/xurls#25]
The certificate for mvdan.cc has expired today resulting in the following error:
```
github.com/golang/dep
The following errors occurred while deducing packages:
  * "mvdan.cc/xurls": unable to deduce repository and source type for "mvdan.cc/xurls": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://mvdan.cc/xurls?go-get=1": Get https://mvdan.cc/xurls?go-get=1: x509: certificate has expired or is not yet valid
```

**Comment by JelteF** [comment]
We have the same problem. Our solution was to replace all imports to mvdan.cc/xurls, to github.com/mvdan/xurls

**Comment by rubyroobs** [comment]
@JelteF beat me to it :) yes this was also our solution. Seems better going forward - @mvdan might I suggest updating your documentation to use `github.com` going forward so this issue does not occur again?

**Comment by mvdan** [comment]
Apologies; not sure how that happened. Fixed.

You should not be using the github import paths. The module path is what's on the README.

The Go module proxy is live now, so you can always fetch from there if my domain or github are down.
