### ISSUE TITLE
Error with Input containing long lines

### ISSUE THREAD

**Issue by uggyuggy** [mvdan/xurls#28]
Hi, thank's for providing xurls.

I came across the following error when input file contains quite long lines
```
$ printf 'tototutu%.0s' {1..9000} > /tmp/a
$ xurls -r  /tmp/a
bufio.Scanner: token too long
$
$ printf 'tototutu%.0s' {1..5000} > /tmp/b
$ xurls -r /tmp/b
$
```
Just wanted to report such strange case with long line could happen...
As I'm not a good golang coder, It's better I'm not submitting PR.

**Comment by mvdan** [comment]
Thanks for raising this issue. It does look like there's an internal limit on the line length, which isn't ideal. I'll see what can be done.

**Comment by mvdan** [comment]
I've verified that this fixes your example above. If you still run into issues, let me know.

The downside of the new approach is that if an input line is 1GB long, the program will allocate a lot of memory. But I don't think that's worse than erroring directly.

**Comment by uggyuggy** [comment]
Thank you 👍

**Comment by uggyuggy** [comment]
Hi,
Thank's for code update. Error looks solved.

But it looks this commit introduce new "problem" with IDN TLD not matching anymore:

Before this commit:
```
👉 echo "test.网店" | ./xurls -r
test.网店
👉 
```

After this commit:
```
👉 echo "test.网店" | ./xurls -r
👉 
```

**Comment by mvdan** [comment]
Thanks for noticing - not sure what happened there.

**Comment by uggyuggy** [comment]
Thank you 👍
