### ISSUE TITLE
Incorrectly matches ::

### ISSUE THREAD

**Issue by HalosGhost** [mvdan/xurls#3]
This bug predates the arbitrary protocol string matching commit.

Currently, ``xurls``'s regexps match ``::`` as a valid URL

**Comment by mvdan** [comment]
This is probably due to the ipv6 regex, will investigate further.

**Comment by mvdan** [comment]
Open to suggestions about a more strict regex string.

The ipv4 one is still kinda approachable but the ipv6 one is madness.

**Comment by HalosGhost** [comment]
I wonder if ``::`` is actually a valid IPv6 address…

**Comment by mvdan** [comment]
This is actually not what we're after, we're not validating addresses nor urls (I will clarify this in the README). For urls that don't start with a scheme, we're just interested in whether they *look* like urls. `::/path` definitely doesn't look like one to me, not to mention `::` alone.

**Comment by HalosGhost** [comment]
sgtm.
