### ISSUE TITLE
README example is confusing to some users

### ISSUE THREAD

**Issue by kevinburkemeter** [mvdan/xurls#31]
If you were worried that people were accidentally compiling the regex on every function invocation - I just hit some code that was doing this, and as expected it had pretty poor performance (on the order of hundreds of gigabytes of memory allocated for a simple program).

It might be worthwhile to switch up the examples to create one Relaxed() and parse multiple URL's (or non URL's as the case may be) with it.

**Comment by mvdan** [comment]
Yikes. I expected it would be obvious enough given the func call, and this explicit note I added:

> Note that the funcs compile regexes, so avoid calling them repeatedly.

Do you think it's worth expanding the example? Maybe it would help some users. But if those users already skip the docs, I'm not sure if I can help them that much.

**Comment by kevinburkemeter** [comment]
I think in this case the person copied the example but the entire thing in every case... how about this? It would add four lines.

```go
import "mvdan.cc/xurls/v2"

func main() {
	var urlFinder = xurls.Relaxed()
	urlFinder.FindString("Do gophers live in golang.org?") // "golang.org"
	urlFinder.FindString("This string does not have a URL") // nil
	var strictFinder = xurls.Strict()
	strictFinder.FindAllString("must have scheme: http://foo.com/.", -1) // []string{"http://foo.com/"}
	strictFinder.FindAllString("no scheme, no match: foo.com", -1) // nil
}
```

**Comment by mvdan** [comment]
Sounds good, thanks!
