### ISSUE TITLE
xurls command not found

### ISSUE THREAD

**Issue by reijin90** [mvdan/xurls#36]
Hi!

For me, the install fails:
```
user@tools:/tmp/tmp.JsYwNTDgZX$ cd $(mktemp -d); go mod init tmp; GO111MODULE=on go get mvdan.cc/xurls/v2/cmd/xurls
go: creating new go.mod: module tmp
user@tools:/tmp/tmp.MFwKzoKsW4$ xurls
xurls: command not found
user@tools:/tmp/tmp.MFwKzoKsW4$ echo "Do gophers live in http://golang.org?" | xurls
xurls: command not found
```
I'm running `go version go1.13.5 linux/amd64` installed, by following the official guide: https://golang.org/doc/install

Not sure what causes this issue.

**Comment by mvdan** [comment]
You most likely did not set up your `$PATH` to include `$GOPATH/bin` or its default, `$HOME/go/bin`.
