### ISSUE TITLE
cannot find package "mvdan.cc/xurls/v2"

### ISSUE THREAD

**Issue by wzkun** [mvdan/xurls#37]
go get -u -v mvdan.cc/xurls/v2          
get "mvdan.cc/xurls/v2": found meta tag get.metaImport{Prefix:"mvdan.cc/xurls", VCS:"git", RepoRoot:"https://github.com/mvdan/xurls"} at //mvdan.cc/xurls/v2?go-get=1
get "mvdan.cc/xurls/v2": verifying non-authoritative meta tag
mvdan.cc/xurls (download)
package mvdan.cc/xurls/v2: cannot find package "mvdan.cc/xurls/v2" in any of:
	/Users/wzkun/.gvm/gos/go1.14beta1/src/mvdan.cc/xurls/v2 (from $GOROOT)
	/Users/wzkun/.gvm/pkgsets/go1.14beta1/global/src/mvdan.cc/xurls/v2 (from $GOPATH)

**Comment by mvdan** [comment]
Please follow the README instructions.

    cd $(mktemp -d); go mod init tmp; GO111MODULE=on go get mvdan.cc/xurls/v2/cmd/xurls
