### ISSUE TITLE
/bin/sh -c dep ensure -vendor-only fails with  remote repository at https://github.com/mvdan/xurls does not exist, or is inaccessible: : exit status 128`

### ISSUE THREAD

**Issue by lauraeci** [mvdan/xurls#39]
Hi! 

Not sure how to get around this issue with dep ensure. We're using go 1.12 and dep ensure so trying to lock the repo down to 2.1.0 for 1.12 support. Running through a docker image on linux-amd64

```grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export mvdan.cc/xurls: remote repository at https://github.com/mvdan/xurls does not exist, or is inaccessible: : exit status 128```

Thinking this line in our docker file is breaking things...
"RUN git config --global url.ssh://git@github.com/.insteadOf https://github.com/"

Any tips would be very helpful. Looked up solutions for dep and none of those solutions work. 

Thank you,
-Laura

Gopkg.toml
```
[[constraint]]
  name = "mvdan.cc/xurls"
  version = "2.1.0"
```

Gopkg.lock:
```[[projects]]
  digest = "1:bd1896d9d8de29f9656f936e2cc51b682f4ea0be9da662ec93571fec18d83f61"
  name = "mvdan.cc/xurls"
  packages = ["."]
  pruneopts = ""
  revision = "aca318f079078cc3677a81e7f7d89df859f4f4b2"
  version = "v2.1.0"```

**Comment by mvdan** [comment]
Sorry, I don't know. I haven't used dep in at least three years at this point. Go 1.12 won't be supported much longer, and dep has been semi-abandoned for a while, so my suggestion would be to use a newer version of Go and the latest version of xurls. You should also look at modules, which is what this project uses too.

**Comment by lauraeci** [comment]
Yep, that's probably the best recommendation long-term, we're a little behind 😜 Thanks, @mvdan.
