### ISSUE TITLE
Matching does not recognize fragments

### ISSUE THREAD

**Issue by HalosGhost** [mvdan/xurls#4]
This is not to say that this practice is a good one. But it is very common for URLs to include a section identifier or something similar following a ``#``.

At the moment, ``xurls`` ignores these parts of the URL. So, if I pipe the text "https://google.com/#testingthings" through ``xurls``, ``xurls`` only matches ``https://google.com/``.

The correct solution is to recognize and respect these fragments.

**Comment by mvdan** [comment]
Huh, it should. Will investigate.

**Comment by mvdan** [comment]
Looks like I forgot adding '#' to the array of supported chars. Added a test case for it too. Thanks for noticing!

**Comment by HalosGhost** [comment]
:+1:
