### ISSUE TITLE
Relaxed mode wrong matching 

### ISSUE THREAD

**Issue by mseld** [mvdan/xurls#40]
### Description 
**Input**
```
Hello User you have been chosen to win journey to City,Country for 7 day(s)
##enjoy.it
Please Visit our website shopping.com/profile/joe 
```

**Actual Detection**
enjoy.it
shopping.com/profile/joe

**Expected**
shopping.com/profile/joe

More examples
```sh
echo "##google.com" | xurls -r
echo "##enjoy.it" | xurls -r
```

**Comment by mvdan** [comment]
This looks correct, though - `enjoy.it` is a valid URL. There isn't any character that you can add to its left to not make it a valid URL that we pick up.

If this is markdown or HTML, you might have more success if you only use xurls on paragraph bodies, and not on titles.
