### ISSUE TITLE
missing postgresql in schemes

### ISSUE THREAD

**Issue by lucmichalski** [mvdan/xurls#42]
Hi mate,

Hope you are doing all well !

I was playing with xurls with some tricky urls and I noticed that postresql scheme is missing, for eg:
```sh
postgres://user:pass@host.com:5432/path?k=v#f
```

Can you add it plz ? :-)

Cheers,
Luc

**Comment by mvdan** [comment]
I think that's reasonable. I'm surprised that https://www.iana.org/assignments/uri-schemes/uri-schemes-1.csv does not include it.

Do you know of a URL/URI scheme list that would include postgres? I would rather not start hard-coding extra cases like postgres. If application config URI schemes are not included in the CSV above, we could perhaps find another list that does include those.
