### ISSUE TITLE
Managing duplicate URLs?

### ISSUE THREAD

**Issue by 097115** [mvdan/xurls#45]
Would be great if `xurls` could remove duplicate URLs if there are any.

**Comment by mvdan** [comment]
Please be more specific. Do you mean the Go API, or the command line tool? How would this actually look like?

**Comment by 097115** [comment]
Sorry :)

I meant the CLI tool, yes. If a list, piped to it, contains a few instances of the same URL, like `http://abc.com/path/doc`, it would be great if `xurls` could detect it and keep only one entry.

**Comment by mvdan** [comment]
Why not just do `xurls | sort -u`?

**Comment by 097115** [comment]
Oh, and you are right indeed :). Somehow didn't think about it. 

Thanks :)
