### ISSUE TITLE
Email support

### ISSUE THREAD

**Issue by ferhatelmas** [mvdan/xurls#46]
`"Hi, this is my email me@example.com"`

This extracts `example.com` which isn't useful by its own. I would expect to have the complete email address or it's being skipped.

What can be done for email addresses?

**Comment by mvdan** [comment]
Is there a reason you would expect email addresses to match? This package is about matching URLs, and email addresses aren't URLs. See https://github.com/mvdan/xurls/commit/3a43cc764aca9dc4eb4b0581938b6b58934b58f9.

Then again, the relaxed mode matches `example.com`, which is technically not a URL either. So matching `me@example.com` is probably better.

**Comment by ferhatelmas** [comment]
This explanation makes sense. 

Right now, it does a partial work and getting only domain misleading because if I had known it was a part of email address, I would ignore too but can't act on it since this information is lost.

Having a flag to return emails or ignore would be better.

**Comment by ferhatelmas** [comment]
@mvdan Open to add this functionality back and a flag maybe to ignore them in the result?

**Comment by mvdan** [comment]
I was writing a comment explaining why this is not a trivial change, but then I realised it would take me less time to just do it than to try to explain why I haven't done it yet.

**Comment by ferhatelmas** [comment]
Thanks for the update, can we also tag it please ?

**Comment by mvdan** [comment]
I will do a tag in the next few days. You can use master in the meantime.
