### ISSUE TITLE
go: error loading module requirements  

### ISSUE THREAD

**Issue by leon12171** [mvdan/xurls#47]
I don't understand how to solve this problem. Help me please.
![IMG_20210317_170228](https://user-images.githubusercontent.com/24985843/111489949-48456c80-8743-11eb-9e01-206694f2f235.jpg)

**Comment by mvdan** [comment]
See https://github.com/golang/go/wiki/Questions. It sounds like you edited go.mod in a way that is invalid. That doesn't seem like a bug in this module.

**Comment by leon12171** [comment]
> См. [Https://github.com/golang/go/wiki/Questions](https://github.com/golang/go/wiki/Questions) . Похоже, вы отредактировали go.mod некорректно. Это не похоже на ошибку в этом модуле.

![IMG_20210317_192606](https://user-images.githubusercontent.com/24985843/111511102-13dbab80-8757-11eb-87ed-cb8dbb5e269b.jpg)

**Comment by mvdan** [comment]
Sorry, but I'm not providing support. See the wiki link I shared earlier.
