### ISSUE TITLE
character ranges can optionally be limited to ascii

### ISSUE THREAD

**Issue by ZLeQ** [mvdan/xurls#69]
the xurls matches a lot of CJK characters
i need to control the Unicode range
can you provide an option to match only ascii?

case：
https://en.wikipedia.org/wiki/Unicode介绍了Unicode知识

**Comment by mvdan** [comment]
What is the use case? That is presumably all a valid URL, as you can see GitHub marks it as such and you can enter it into a browser and it works without any spaces.

**Comment by mvdan** [comment]
No response; closing.
