### ISSUE TITLE
Arbitrary domain matching

### ISSUE THREAD

**Issue by HalosGhost** [mvdan/xurls#7]
At the moment, ``xurls`` matches against a list of TLDs from the IANA; however, as that list is ever-changing, and since there are plenty of domains that may be valid but are not administered by the IANA, I would propose an option to match arbitrary TLDs.

This would dramatically simplify the matching code and make it far more flexible.

**Comment by mvdan** [comment]
To be honest, I did the whole IANA stuff because I wanted to play with `go generate` and prove to myself that I could get the TLD regex working with it.

Let me think about this for a bit...

**Comment by mvdan** [comment]
Oh, btw - the TLD regex is only used for the relaxed matching. Any tld is matched in the strict matching. I don't think `foo.barbarbarbar/path` should match, for example. Or stuff like `foo.bar` where bar is clearly not a TLD is often everywhere.

**Comment by mvdan** [comment]
I've thought more about this and convinced myself that the current approach is correct. The only thing I see we could do is match `foo.bar/path` where `.bar` is not a known TLD, whereas `foo.bar` would not match to not have too many false positives.

If you'd like that added, or have a better alternative, please reopen and let me know.
